command:
  - python
  - app.py
env:
  - name: DATABRICKS_HOST
    value: https://e2-demo-field-eng.cloud.databricks.com
  - name: DATABRICKS_TOKEN
    value: your_token
  - name: DATABRICKS_ENDPOINT
    value: ali_azzouz_football_football_cv
